import { createElement, type ComponentType, type ReactElement } from 'react'
import type { LucideIcon } from 'lucide-react-native'
import {
  Home,
  Utensils,
  Car,
  ShoppingCart,
  Gamepad2,
  HeartPulse,
  GraduationCap,
  Circle,
  Wallet,
  CreditCard,
  Coffee,
  Plane,
  Dumbbell,
  PawPrint,
  Music,
  Clapperboard,
  Smartphone,
  Zap,
  Gift,
  Briefcase,
  Wrench,
  Leaf,
  Heart,
  Repeat,
  Tag,
  Baby,
  Bus,
  Bike,
  Fuel,
  Shirt,
  Scissors,
  Sparkles,
  Stethoscope,
  Pill,
  Building2,
  Landmark,
  Wifi,
  Tv,
  BookOpen,
  Dog,
  Cat,
  Flower2,
  Umbrella,
  Ticket,
  Wine,
  Pizza,
  Salad,
  IceCreamCone,
  ShoppingBag,
  Store,
  Receipt,
  PiggyBank,
  Coins,
  Banknote,
  Train,
  Ship,
  Hotel,
  Tent,
  TreePalm,
  Mountain,
  Camera,
  Headphones,
  Mic,
  Paintbrush,
  Hammer,
  Plug,
  Droplets,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Star,
} from 'lucide-react-native'

export type LucideFinanceName = keyof typeof LUCIDE_FINANCE_ICONS

export const LUCIDE_FINANCE_ICONS = {
  home: Home,
  utensils: Utensils,
  car: Car,
  'shopping-cart': ShoppingCart,
  'gamepad-2': Gamepad2,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  circle: Circle,
  wallet: Wallet,
  'credit-card': CreditCard,
  coffee: Coffee,
  plane: Plane,
  dumbbell: Dumbbell,
  'paw-print': PawPrint,
  music: Music,
  clapperboard: Clapperboard,
  smartphone: Smartphone,
  zap: Zap,
  gift: Gift,
  briefcase: Briefcase,
  wrench: Wrench,
  leaf: Leaf,
  heart: Heart,
  repeat: Repeat,
  tag: Tag,
  baby: Baby,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  shirt: Shirt,
  scissors: Scissors,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  pill: Pill,
  'building-2': Building2,
  landmark: Landmark,
  wifi: Wifi,
  tv: Tv,
  'book-open': BookOpen,
  dog: Dog,
  cat: Cat,
  'flower-2': Flower2,
  umbrella: Umbrella,
  ticket: Ticket,
  wine: Wine,
  pizza: Pizza,
  salad: Salad,
  'ice-cream': IceCreamCone,
  'shopping-bag': ShoppingBag,
  store: Store,
  receipt: Receipt,
  'piggy-bank': PiggyBank,
  coins: Coins,
  banknote: Banknote,
  train: Train,
  ship: Ship,
  hotel: Hotel,
  tent: Tent,
  palmtree: TreePalm,
  mountain: Mountain,
  camera: Camera,
  headphones: Headphones,
  mic: Mic,
  paintbrush: Paintbrush,
  hammer: Hammer,
  plug: Plug,
  droplets: Droplets,
  flame: Flame,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  star: Star,
} as const satisfies Record<string, LucideIcon>

export const LUCIDE_FINANCE_ICON_NAMES = Object.keys(LUCIDE_FINANCE_ICONS) as LucideFinanceName[]

const ION_TO_LUCIDE: Record<string, LucideFinanceName> = {
  'home-outline': 'home',
  'restaurant-outline': 'utensils',
  'car-outline': 'car',
  'cart-outline': 'shopping-cart',
  'game-controller-outline': 'gamepad-2',
  'medkit-outline': 'heart-pulse',
  'school-outline': 'graduation-cap',
  'ellipse-outline': 'circle',
  'wallet-outline': 'wallet',
  'card-outline': 'credit-card',
  'cafe-outline': 'coffee',
  'airplane-outline': 'plane',
  'fitness-outline': 'dumbbell',
  'paw-outline': 'paw-print',
  'musical-notes-outline': 'music',
  'film-outline': 'clapperboard',
  'phone-portrait-outline': 'smartphone',
  'flash-outline': 'zap',
  'gift-outline': 'gift',
  'briefcase-outline': 'briefcase',
  'construct-outline': 'wrench',
  'leaf-outline': 'leaf',
  'heart-outline': 'heart',
  'repeat-outline': 'repeat',
  'pricetag-outline': 'tag',
}

export function resolveLucideFinanceName(raw: string | undefined): LucideFinanceName
{
  if (raw && raw in LUCIDE_FINANCE_ICONS) return raw as LucideFinanceName
  if (raw && ION_TO_LUCIDE[raw]) return ION_TO_LUCIDE[raw]
  return 'circle'
}

export function LucideFinanceIcon({
  name,
  size = 18,
  color,
}: {
  name: string
  size?: number
  color: string
}): ReactElement
{
  const Icon = LUCIDE_FINANCE_ICONS[resolveLucideFinanceName(name)] as unknown as ComponentType<{
    size: number
    color: string
    strokeWidth: number
  }>
  return createElement(Icon, { size, color, strokeWidth: 1.75 })
}
