"""add_tarefa_templates

Revision ID: b76bf9297639
Revises: e5a8b3c7d2f1
Create Date: 2026-04-15 11:40:03.223745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76bf9297639'
down_revision: Union[str, None] = 'e5a8b3c7d2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('subtarefas_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_templates_id'), 'tarefa_templates', ['id'], unique=False)
    op.drop_index('idx_anotacoes_fts', table_name='anotacoes', postgresql_using='gin')
    op.create_index(op.f('ix_anotacoes_id'), 'anotacoes', ['id'], unique=False)
    op.create_index(op.f('ix_despesas_id'), 'despesas', ['id'], unique=False)
    op.drop_index('ix_diario_humor_data', table_name='diario_humor')
    op.drop_index('ix_diario_humor_usuario_id', table_name='diario_humor')
    op.create_index(op.f('ix_diario_humor_id'), 'diario_humor', ['id'], unique=False)
    op.drop_index('ix_entradas_diario_data', table_name='entradas_diario')
    op.drop_index('ix_entradas_diario_usuario_id', table_name='entradas_diario')
    op.create_index(op.f('ix_entradas_diario_id'), 'entradas_diario', ['id'], unique=False)
    op.drop_index('ix_habitos_usuario_id', table_name='habitos_diarios')
    op.create_index(op.f('ix_habitos_diarios_id'), 'habitos_diarios', ['id'], unique=False)
    op.drop_index('ix_historico_habito_id', table_name='historico_habitos')
    op.drop_index('ix_historico_habitos_habito_id', table_name='historico_habitos')
    op.drop_index('ix_historico_habitos_usuario_id', table_name='historico_habitos')
    op.drop_index('ix_historico_usuario_id', table_name='historico_habitos')
    op.create_index(op.f('ix_historico_habitos_id'), 'historico_habitos', ['id'], unique=False)
    op.create_index(op.f('ix_integracoes_id'), 'integracoes', ['id'], unique=False)
    op.drop_index('ix_labels_usuario_id', table_name='labels')
    op.create_index(op.f('ix_labels_id'), 'labels', ['id'], unique=False)
    op.drop_index('ix_medicamentos_usuario_id', table_name='medicamentos')
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    op.drop_index('ix_notificacoes_lida', table_name='notificacoes')
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.drop_index('ix_palavras_chave_user_id', table_name='palavras_chave')
    op.create_index(op.f('ix_palavras_chave_id'), 'palavras_chave', ['id'], unique=False)
    op.create_index(op.f('ix_preferencias_usuario_id'), 'preferencias_usuario', ['id'], unique=False)
    op.drop_index('ix_sessoes_foco_user_id', table_name='sessoes_foco')
    op.create_index(op.f('ix_sessoes_foco_id'), 'sessoes_foco', ['id'], unique=False)
    op.drop_index('ix_subtarefas_tarefa_id', table_name='subtarefas')
    op.create_index(op.f('ix_subtarefas_id'), 'subtarefas', ['id'], unique=False)
    op.drop_index('ix_tarefa_labels_label_id', table_name='tarefa_labels')
    op.drop_index('ix_tarefa_labels_tarefa_id', table_name='tarefa_labels')
    op.create_index(op.f('ix_tarefa_labels_id'), 'tarefa_labels', ['id'], unique=False)
    op.alter_column('tarefas_unificadas', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index('idx_tarefas_fts', table_name='tarefas_unificadas', postgresql_using='gin')
    op.drop_index('ix_tarefas_score_urgencia', table_name='tarefas_unificadas')
    op.drop_index('ix_tarefas_status', table_name='tarefas_unificadas')
    op.drop_index('ix_tarefas_usuario_id', table_name='tarefas_unificadas')
    op.create_index(op.f('ix_tarefas_unificadas_usuario_id'), 'tarefas_unificadas', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('usuarios_email_key', 'usuarios', type_='unique')
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False)
    op.create_unique_constraint('usuarios_email_key', 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_tarefas_unificadas_usuario_id'), table_name='tarefas_unificadas')
    op.create_index('ix_tarefas_usuario_id', 'tarefas_unificadas', ['usuario_id'], unique=False)
    op.create_index('ix_tarefas_status', 'tarefas_unificadas', ['status'], unique=False)
    op.create_index('ix_tarefas_score_urgencia', 'tarefas_unificadas', [sa.literal_column('score_urgencia DESC')], unique=False)
    op.create_index('idx_tarefas_fts', 'tarefas_unificadas', [sa.literal_column("to_tsvector('portuguese'::regconfig, (COALESCE(titulo, ''::character varying)::text || ' '::text) || COALESCE(descricao, ''::text))")], unique=False, postgresql_using='gin')
    op.alter_column('tarefas_unificadas', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_tarefa_labels_id'), table_name='tarefa_labels')
    op.create_index('ix_tarefa_labels_tarefa_id', 'tarefa_labels', ['tarefa_id'], unique=False)
    op.create_index('ix_tarefa_labels_label_id', 'tarefa_labels', ['label_id'], unique=False)
    op.drop_index(op.f('ix_subtarefas_id'), table_name='subtarefas')
    op.create_index('ix_subtarefas_tarefa_id', 'subtarefas', ['tarefa_id'], unique=False)
    op.drop_index(op.f('ix_sessoes_foco_id'), table_name='sessoes_foco')
    op.create_index('ix_sessoes_foco_user_id', 'sessoes_foco', ['user_id'], unique=False)
    op.drop_index(op.f('ix_preferencias_usuario_id'), table_name='preferencias_usuario')
    op.drop_index(op.f('ix_palavras_chave_id'), table_name='palavras_chave')
    op.create_index('ix_palavras_chave_user_id', 'palavras_chave', ['user_id'], unique=False)
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.create_index('ix_notificacoes_lida', 'notificacoes', ['lida'], unique=False)
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.create_index('ix_medicamentos_usuario_id', 'medicamentos', ['usuario_id'], unique=False)
    op.drop_index(op.f('ix_labels_id'), table_name='labels')
    op.create_index('ix_labels_usuario_id', 'labels', ['usuario_id'], unique=False)
    op.drop_index(op.f('ix_integracoes_id'), table_name='integracoes')
    op.drop_index(op.f('ix_historico_habitos_id'), table_name='historico_habitos')
    op.create_index('ix_historico_usuario_id', 'historico_habitos', ['usuario_id'], unique=False)
    op.create_index('ix_historico_habitos_usuario_id', 'historico_habitos', ['usuario_id'], unique=False)
    op.create_index('ix_historico_habitos_habito_id', 'historico_habitos', ['habito_id'], unique=False)
    op.create_index('ix_historico_habito_id', 'historico_habitos', ['habito_id'], unique=False)
    op.drop_index(op.f('ix_habitos_diarios_id'), table_name='habitos_diarios')
    op.create_index('ix_habitos_usuario_id', 'habitos_diarios', ['usuario_id'], unique=False)
    op.drop_index(op.f('ix_entradas_diario_id'), table_name='entradas_diario')
    op.create_index('ix_entradas_diario_usuario_id', 'entradas_diario', ['usuario_id'], unique=False)
    op.create_index('ix_entradas_diario_data', 'entradas_diario', ['data'], unique=False)
    op.drop_index(op.f('ix_diario_humor_id'), table_name='diario_humor')
    op.create_index('ix_diario_humor_usuario_id', 'diario_humor', ['usuario_id'], unique=False)
    op.create_index('ix_diario_humor_data', 'diario_humor', ['data'], unique=False)
    op.drop_index(op.f('ix_despesas_id'), table_name='despesas')
    op.drop_index(op.f('ix_anotacoes_id'), table_name='anotacoes')
    op.create_index('idx_anotacoes_fts', 'anotacoes', [sa.literal_column("to_tsvector('portuguese'::regconfig, (COALESCE(titulo, ''::character varying)::text || ' '::text) || COALESCE(conteudo, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_tarefa_templates_id'), table_name='tarefa_templates')
    op.drop_table('tarefa_templates')
    # ### end Alembic commands ###
