// Tokens visuais — Configurações (alinha ao design system AXEL)

export const SETTINGS = {
  title: 'text-xl sm:text-2xl font-display text-ink tracking-tight',
  subtitle: 'text-ink-muted text-sm mt-0.5',
  sectionTitle: 'text-lg font-display text-ink',
  sectionHint: 'text-xs text-ink-muted mt-1',
  card: 'bg-card border border-line rounded-sl',
  cardMuted: 'bg-chrome/40 border border-line rounded-sl',
  navActive: 'bg-chrome text-ink border border-line',
  navIdle: 'text-ink-muted hover:text-ink hover:bg-chrome/60',
  rowTitle: 'text-[15px] font-semibold text-ink',
  rowHint: 'text-xs text-ink-muted mt-0.5',
  label: 'text-sm font-medium text-ink',
  body: 'text-[13px] text-ink-muted',
  iconMuted: 'text-ink-muted',
  iconAccent: 'text-accent',
  accentPanel: 'border border-accent/20 bg-gradient-to-br from-accent/[0.06] to-transparent rounded-sl',
  accentIconBg: 'bg-accent/10',
  successBorder: 'border-concluido/20',
  successBg: 'bg-concluido/[0.04]',
  successText: 'text-concluido',
  successIconBg: 'bg-concluido/10',
  input: 'w-full bg-chrome border border-line rounded-sl px-4 py-2.5 text-sm text-ink placeholder:text-ink-muted outline-none focus:border-accent/50 transition',
  textarea: 'w-full bg-chrome border border-line rounded-sl px-4 py-3 text-[13px] text-ink placeholder:text-ink-muted outline-none focus:border-accent/50 transition resize-none',
  btnSecondary: 'px-4 py-2 text-[13px] font-medium rounded-sl border border-line text-ink-muted hover:text-ink hover:bg-chrome transition-colors',
  btnPrimary: 'px-4 py-2 text-[13px] font-semibold rounded-sl bg-accent text-white hover:bg-accent-hover transition-colors disabled:opacity-40',
  tag: 'px-2.5 py-1 text-[11px] font-medium bg-accent/10 text-accent border border-accent/20 rounded-sl',
  progressTrack: 'h-1 rounded-full bg-chrome mb-4 overflow-hidden',
  progressBar: 'h-full bg-accent transition-all duration-500',
  divider: 'border-t border-line',
} as const
