import { chromium } from '@playwright/test'
import { join } from 'node:path'
const out = process.env.SHOT_DIR
const b = await chromium.launch({ channel: 'chrome' })
const p = await b.newPage({ viewport: { width: 390, height: 844 } })
const errs = []
p.on('pageerror', (e) => errs.push(e.message))
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()) })
let n = 0
const shot = async (name) =>
{
  await p.waitForTimeout(700)
  const h = await p.evaluate(() =>
  {
    let best = 0
    for (const el of document.querySelectorAll('*'))
    {
      const s = getComputedStyle(el)
      if (/(auto|scroll)/.test(s.overflowY) && el.scrollHeight > el.clientHeight + 20 && el.clientWidth > 300 && el.offsetParent !== null)
        best = Math.max(best, el.scrollHeight + (innerHeight - el.clientHeight))
    }
    return best
  })
  if (h > 844) await p.setViewportSize({ width: 390, height: Math.min(h + 40, 9000) })
  await p.waitForTimeout(500)
  await p.screenshot({ path: join(out, `onb-${String(++n).padStart(2, '0')}-${name}.png`) })
  await p.setViewportSize({ width: 390, height: 844 })
}
const click = async (t, exact = true) => { await p.getByText(t, { exact }).last().click({ force: true }); await p.waitForTimeout(600) }
await p.goto('http://localhost:8082/login', { waitUntil: 'networkidle', timeout: 90000 })
await p.waitForTimeout(1500)
const light = p.getByLabel('Usar tema claro')
if (await light.count()) await light.first().click()
await p.getByText('Continuar como convidado').first().click()
await p.getByText('Bem-vindo ao Simply Life').waitFor({ timeout: 30000 })
await shot('welcome')
await click('Escura')
await shot('welcome-dark')
await click('Começar')
await p.waitForTimeout(1500)
await shot('after-start')
console.log('ERRS', JSON.stringify(errs.slice(0, 8)))
console.log('INPUTS', JSON.stringify(await p.evaluate(() => [...document.querySelectorAll('input,textarea')].map((e) => ({ t: e.tagName, ph: e.getAttribute('placeholder'), vis: e.offsetParent !== null, ro: e.readOnly, dis: e.disabled })))))
await p.locator('input[placeholder="Seu nome"]:visible').first().fill('Mari', { force: true })
await click('Continuar')
await shot('modules')
// tira a Carteira inteira e o Apoio
await p.getByText('Tirar tudo').last().click({ force: true })
await p.waitForTimeout(400)
await click('Apoio emocional')
await shot('modules-after')
await click('Continuar', false)
// Tarefas
await p.locator('input[placeholder="Marcar dentista"]:visible').first().fill('Marcar dentista', { force: true })
await click('Meditar 5 min')
await click('Caminhar')
await shot('tasks')
await click('Continuar')
// Saúde
await p.getByLabel('Aumentar Tamanho do copo').click({ force: true })
await click('Seg'); await click('Qua'); await click('Sex')
await p.locator('input[placeholder="Vitamina D"]:visible').first().fill('Vitamina D', { force: true })
await click('Adicionar remédio')
await shot('health')
await click('Continuar')
await shot('rhythm')
await click('Continuar')
await shot('home')
await click('Continuar')
await shot('summary')
await click('Começar')
await p.waitForTimeout(4000)
await shot('home-after')
await p.getByRole('button', { name: 'Saúde', exact: true }).last().click({ force: true })
await p.waitForTimeout(1500)
await shot('saude')
await p.getByRole('button', { name: 'Tarefas', exact: true }).last().click({ force: true })
await p.waitForTimeout(1500)
await shot('tarefas')
await p.getByRole('button', { name: 'Início', exact: true }).last().click({ force: true })
await p.waitForTimeout(1200)
await p.getByLabel(/^Conta/).first().click({ force: true })
await p.waitForTimeout(800)
await click('Preferências')
await p.waitForTimeout(1500)
await shot('prefs-uso')
await p.getByRole('checkbox', { name: 'Água' }).last().click({ force: true })
await p.waitForTimeout(600)
await shot('prefs-confirm')
await p.getByRole('button', { name: 'Tirar', exact: true }).last().click({ force: true })
await p.waitForTimeout(800)
await p.getByText('Metas', { exact: true }).first().click({ force: true })
await p.waitForTimeout(800)
await shot('prefs-metas')
await p.getByText('Geral', { exact: true }).first().click({ force: true })
await p.waitForTimeout(800)
await shot('prefs-geral')
console.log('ERRS', JSON.stringify(errs.slice(0, 10)))
await b.close()
