import type { LucideIcon } from 'lucide-react'
import {
  BookOpen,
  Calendar,
  Car,
  Clapperboard,
  Coffee,
  Crown,
  Droplets,
  Flame,
  Fuel,
  Gift,
  Heart,
  Hourglass,
  Leaf,
  MessageCircle,
  Moon,
  Pencil,
  Pill,
  QrCode,
  Sandwich,
  ScrollText,
  Shield,
  Shirt,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Target,
  Thermometer,
  Users,
  Utensils,
  Wallet,
  Zap,
} from 'lucide-react'

/** Mesmo peso do menu - stroke 1.75 */
export const AXEL_ICON_STROKE = 1.75

/** id → Lucide. Atalho, refeição, preset e trilha - sem emoji nativo */
export const AXEL_ICON_MAP: Record<string, LucideIcon> = {
  'qr-code': QrCode,
  car: Car,
  utensils: Utensils,
  coffee: Coffee,
  'shopping-cart': ShoppingCart,
  pill: Pill,
  smartphone: Smartphone,
  fuel: Fuel,
  clapperboard: Clapperboard,
  wallet: Wallet,
  'preset-pix': QrCode,
  'preset-uber': Car,
  'preset-almoco': Utensils,
  'preset-cafe': Coffee,
  'preset-mercado': ShoppingCart,
  'preset-farmacia': Pill,
  'preset-assinatura': Smartphone,
  'preset-gasolina': Fuel,
  'preset-lazer': Clapperboard,
  cafe: Coffee,
  almoco: Utensils,
  jantar: Moon,
  lanche: Sandwich,
  mercado: ShoppingCart,
  roupa: Shirt,
  presente: Gift,
  transporte: Car,
  farmacia: Pill,
  lazer: Clapperboard,
  assinatura: Smartphone,
  outro: Pencil,
  task: Zap,
  focus: Target,
  streak: Flame,
  water: Droplets,
  mood: Heart,
  finance: Wallet,
  quest: ScrollText,
  daily_cap: Hourglass,
  chat: MessageCircle,
  thermometer: Thermometer,
  book: BookOpen,
  users: Users,
  calendar: Calendar,
  shield: Shield,
  leaf: Leaf,
  sparkles: Sparkles,
  crown: Crown,
}

export function resolveAxelIcon(id: string | null | undefined): LucideIcon
{
  if (id && AXEL_ICON_MAP[id]) return AXEL_ICON_MAP[id]
  return Wallet
}
