/** Cores sugeridas ao criar categoria */
export const FINANCE_CATEGORY_PRESET_COLORS: string[] = [
  '#3b82f6', '#ef4444', '#10b981', '#f59e0b', '#8b5cf6',
  '#ec4899', '#06b6d4', '#f97316', '#6366f1', '#14b8a6',
  '#22c55e', '#f43f5e', '#a855f7', '#84cc16', '#0ea5e9',
  '#d946ef', '#78716c', '#1e293b', '#fde047', '#fb7185',
  '#2dd4bf', '#e11d48', '#4f46e5', '#ca8a04',
]

/** Ordem de exibição no seletor de ícones */
export const FINANCE_CATEGORY_ICON_IDS: string[] = [
  'Wallet',
  'ShoppingCart',
  'Utensils',
  'Home',
  'Heart',
  'GraduationCap',
  'Gamepad2',
  'Wifi',
  'Plane',
  'Briefcase',
  'Car',
  'Zap',
  'Target',
  'CreditCard',
  'Receipt',
  'Coffee',
  'Shirt',
  'Baby',
  'Dog',
  'Music',
  'Film',
  'Smartphone',
  'Fuel',
  'Bus',
  'Building2',
  'Gift',
  'PiggyBank',
  'TrendingUp',
  'Stethoscope',
  'Dumbbell',
  'BookOpen',
  'Pizza',
  'Landmark',
  'Banknote',
  'Pill',
  'Flower2',
  'Wrench',
  'Sparkles',
  'CircleDollarSign',
  'TreePine',
]
